id = "test"
displayName = "Display Test"
material = "IRON_HOE"
customModelData = 0


shootParticle = "FLAME"
type = "AR"

bulletsPerShot = 1
range = 50.0
zoom = 5
reloadTimeInTicks = 30
fireRate = 300
maxAmmo = 30

headDamage = 8.0
bodyDamage = 5.0
legDamage = 3.0

spread = 2.0
sneakSpread = 0.5

sounds = []