name: Prismarin-Security
version: 1.0
api-version: 1.18
main: in.prismar.security.Security
author: Maga
description: Prismarin-Security made by ReaperMaga
depend: [Prismarin-Core]
softdepend: [Prismarin-Essentials]