name: Prismarin-Game
version: 1.0
api-version: 1.18
main: in.prismar.game.Game
author: Maga
description: Prismarin-Game made by ReaperMaga
depend: [Prismarin-Core]
softdepend: [Multiverse-Core, Prismarin-Essentials, Prismarin-Compass, MythicMobs]